### ISSUE TITLE
주제 및 일정

### ISSUE THREAD

**Issue by WinterStar915** [WinterStar915/KH-Team-Project#1]
## 주제 선정 및 개발 목적/주안점 계획서 작성
- 최다연님이 계획서 정리 진행

[프로젝트 계획서(최종).pdf](https://github.com/WinterStar915/KH-Team-Project/files/9415491/default.pdf)

![Image](https://user-images.githubusercontent.com/94954921/186403156-fa6efe6b-4131-4b10-8064-a3df380ea78e.png)

## 개발 일정
- 박민영님이 간트 차트 작성 진행

[팀프로젝트일정.xlsx](https://github.com/WinterStar915/KH-Team-Project/files/9415140/default.xlsx)

![Image](https://user-images.githubusercontent.com/94954921/186392417-bf7ef41c-cc0d-46c7-ba55-dea1ad28c7d1.png)

**Comment by WinterStar915** [comment]
서비스 되는 웹 페이지 참고 필요
ex)  도서대출 프로그램, 쇼핑몰, 잡코리아 등

**Comment by QQU2** [comment]
*Web Content: 중．고등 과목별 질문 게시판

>> 하위기능<<
   - 회원가입, 로그인
   - 과목별 질문 게시판
   - 선생님, 학생 페이지
   - 선생님들의 짧은 스낵지식 동영상 게시판
   - 관련 문제집, 서적 판매 페이지

**Comment by WinterStar915** [comment]
여행 관련 서비스 상품 Web (참고 사이트 : www.booking.com, https://www.myrealtrip.com)
- 사이트 목적
 항공권 예약 : 항공권 조회 사이트로 연결
 숙소 예약 
 렌터카
 패키지&투어 여행
 숙소/여행 후기(게시판)

- 하위기능
 회원가입, 로그인
 구매자, 판매자, 관리자 구분
 -- 구매자 : 항공권 티켓 예약, 숙소, 렌터카, 패키지&투어 여행 구입(상품 구입자)
 -- 판매자 : 숙소 등록, 렌터카 등록, 패키지 상품 등록(상품 판매자)
 -- 관리자 : 구매자, 판매자 회원 관리, 리뷰 관리
 숙소 리뷰 : 후기, 별점등

**Comment by oni96oni** [comment]
저는 간단한 쇼핑몰 생각하구 있었습니다.

1. 회원가입(주소 API 연동, 이메일 인증, ajax 통한 아이디 중복검사)
2. 관리자 페이지(인터셉터 적용, 상품관리, 회원관리)
3. 업로드(이미지 등록, 수정, 삭제)
4. 검색(&페이징)
5. 구매(장바구니, 포인트 사용)
6. 댓글(등록, 수정, 삭제)

**Comment by oxoxhub** [comment]
영화 예매 사이트

핵심 기능 2~3가지
1.영화 예매 및 영화 리뷰 작성
2.영화 검색 및 조회
3.극장 정보 및 상영 스케줄 조회

로그인 (소셜 로그인/ 아이디 기억하기),
회원가입 (sms인증), 
마이페이지 (수정/탈퇴), 
게시글 등록/조회/수정/삭제,
댓글 등록/수정/삭제, 
공지사항, 
챗봇(실시간 대화),
결제기능(결제, 결제내역조회, 장바구니, 환불) 
결제 시스템 (카카오 페이/ 네이버 페이)
관리기능(회원관리, 게시글관리, 신고관리, 상품관리, 주문결제관리)

저는 여러 기능들을 최대한 모아봤습니다.

**Comment by minnie8211** [comment]
쇼핑몰

필요한 기능
회원가입
로그인
마이페이지
장바구니
구매결제
검색(통합검색, 카테고리별 검색)
리뷰게시판
관리자페이지
- 상품등록/관리
- 주문상품관리
- 고객정보관리

정도의 기능을 생각해봤습니다.
