### ISSUE TITLE
역할분담 및 개발환경

### ISSUE THREAD

**Issue by WinterStar915** [WinterStar915/KH-Team-Project#2]
## 역할 분담
- 조장 :
- 깃 허브 관리자 : 백동빈

## 기능 구현별로 역할 분류
- 홈화면(메인화면) : 박민영님 담당
  - 헤더 메뉴
  - 하단(Footer) 내용 
  - 로그인&회원가입
  - 관리자 페이지
    - 회원 정보 관리(정보 수정, 탈퇴)
    - 수강 정보 관리(결제 정보)
- 마이페이지 : 차시온님 담당
  - 내가 쓴 게시글
  - 내가 쓴 댓글
  - 수강 중 강의
  - 수강 바구니
  - 개인정보 수정
  - 회원 탈퇴
- 커뮤니티 게시판(전체 보기) : 백동빈님 담당
  - Q&A 게시판
  - 팁&노하우 게시판
  - 자유 게시판  
  - (관리자 권한은 모든 게시글, 댓글 삭제 가능)
- 학습 게시판(전체보기) : 이율희님 담당
  - 스터디
  - 프로젝트 모집/모집 완료
  - (관리자 권한은 모든 게시글, 댓글 삭제 가능)
- 강의 게시판(전체보기) : 최다연님 담당
  - 강의 보기
  - 강의 소개
  - 수강평
  - Q&A

## 추가 구현 예정 작업
- 결제 API 구현 추가
- 채팅 기능(1:1 상담 채팅)
- 취업/기업 정보 제공 게시판

**Comment by QQU2** [comment]
1.작은 테이블

- [ ]  role
- [ ]  wishlist
- [ ]  term
- [ ]  agreement,
- [ ]  payment

2. community 

- [ ]  community_board
- [ ]  community_board_statics

3. study

- [ ]  study_board
- [ ]  study_board_statics

4. comment

- [ ]  community_comment
- [ ]  study_comment
- [ ]  community_comment_statics
- [ ]  study_comment_statics

5. lesson

- [ ]  lesson
- [ ]  lesson_manager

 
6. lesson_comment

- [ ]  review_board
- [ ]  QA_board
- [ ]  QA_answer 

7. account
