### ISSUE TITLE
설계 및 분석 - ERD, 테이블 명세, SQL

### ISSUE THREAD

**Issue by WinterStar915** [WinterStar915/KH-Team-Project#5]
## 데이터베이스
- 선정한 주제의 기능 및 정보를 관리하기 위한 데이터베이스 구조 작성
- 기능 구현 또는 정보 관리에 필요한 모든 항목을 수집하고 이를 테이블로 만든다
- 초기에는 테이블 명세로 테이블 스키마를 만들고, 스키마를 토대로 ERD를 작성하여 전체 기능이 관계를 파악하기 쉽게 만든다
- 테이블 명세 및 ERD 작성이 완료된 후에 SQL을 사용하여 실제 데이터베이스를 구현
- 차후 개발을 진행하면서 발생된 추가 정보 및 필요한 정보들은 상호 간 의견 수렴을 통해 확정 짓는다

## SQL문 파일
[RULean_SQL.zip](https://github.com/WinterStar915/KH-Team-Project/files/9451515/RULean_SQL.zip)

## 테이블 명세서
-> 아래 박민영님 코멘트에서 엑셀 파일로 받아주세요

## ERD
[RULearn ERD.zip](https://github.com/WinterStar915/KH-Team-Project/files/9444633/RULearn.ERD.zip)

![Image](https://user-images.githubusercontent.com/94954921/187205670-16c67cfa-0847-405c-b6fd-46f58033b7d6.svg)

**Comment by QQU2** [comment]
##데이터 명세서 논의 사항

1. 강의 수강 관리 테이블 : 강의 결제정보도 같은 테이블에 구성할것인지
2. 약관 동의 테이블: 여러개의 약관이 있을경우, 카테고리테이블을 만들것인지, 회원정보에 컬럼으로 넣을 것인지
3. 좋아요 무제한방지 - STATIC테이블을 만들면 나눠놓은 게시판 테이블 수 만큼 꼭 만들어야 하는지
4. 접근 제한 테이블(나중에 필요하면 추가)

**Comment by minnie8211** [comment]
테이블명세서_220826ver.
