### ISSUE TITLE
설계 및 분석 - 화면 디자인(목업)

### ISSUE THREAD

**Issue by WinterStar915** [WinterStar915/KH-Team-Project#8]
## 화면 목업
- 선정된 주제와 비슷한 타 사이트의 화면 구성을 모방 및 참고하여 현재 진행하는 프로젝트에 적용한다
- 실제 화면 제작을 하기에 앞서 전체적인 페이지 레이아웃(구조)를 선정하고 전체 페이지의 색상 테마를 정하여 작업을 진행 하도록 한다 

## 구성해야 하는 화면
1. 로그인&회원가입
2. 메인 화면
3. 회원정보 페이지(마이페이지 - 회원정보 수정, 게시판 & 댓글 모아보기, 강의 수강, 회원 탈퇴)
4. 커뮤니티 게시판(Q&A, 팁&노하우, 자유게시판)
5. 학습 게시판(전체, 스터디, 프로젝트, 모집중, 모집완료)
6. 온라인 강의
7. 게시판 상세 페이지 & 댓글

## 사이트 이름과 배색 디자인
- 사이트 이름 : RULean(알유런) - 추후 수정 가능
- 배색 디자인 후보
 --https://bootswatch.com/sandstone/ 참고(푸른색 계열)
 --https://bootswatch.com/minty/ 참고 (녹색 계열)

## 각 페이지 디자인
- 목업 최종본(이미지 파일 참고)
- 아래 가장 마지막 코멘트 참고

[목업 최종본.zip](https://github.com/WinterStar915/KH-Team-Project/files/9430563/default.zip)

## 추가해야 할 사항
- 회원가입 페이지 
+) 이용약관 확인 체크
+) 회원가입 완료 후 로그인 페이지로 리다이렉트 처리

- 게시글 상세 페이지
+) 게시글 수정, 삭제 버튼 추가 
+) 댓글 페이징 기능 추가

- 마이 페이지
+) 회원 탈퇴 시 '예' '아니오' 선택지가 나오는 간단한 페이지로 구현

- 유료 서비스에 대한 고객센터(FAQ) 페이지(예정)
FAQ 목록 영역
1:1 고객상담 채팅기능(예정)

**Comment by QQU2** [comment]
1.  홈페이지
2.  마이페이지
  2-1.  회원정보
  2-2.  게시글 모아보기
  2-3.  결제한 강의 모아보기
(회원정보 수정과 댓글 모아보기 화면은 전후 목업과 얼추 비슷할 것 같아 생략했습니다...!)


![Image](https://user-images.githubusercontent.com/97294815/186467589-e6c7943f-607e-4dad-b9de-84e7796849ac.png)
![Image](https://user-images.githubusercontent.com/97294815/186467588-7440a907-811a-40f7-81c3-18680ef649a9.png)
![Image](https://user-images.githubusercontent.com/97294815/186467590-9b8c9e94-7bbd-4155-92dd-d85e1f016539.png)
![Image](https://user-images.githubusercontent.com/97294815/186467591-f7ad2360-8a5d-41b4-8e8f-675ecc68887e.png)

**Comment by WinterStar915** [comment]
4. 커뮤니티 게시판
 - 게시판 메인 화면 예시 2가지
 - Q&A, 자유 게시판, 노하우&팁의 세부 게시판은 중간의 아이콘을 클릭하여 전환
 - 게시판 상세 페이지는 학습 게시판의 디자인과 통일해야 할 수도 있으니 일단 보류했습니다.


[Q&A]
![Image](https://user-images.githubusercontent.com/94954921/186557923-c60af6cb-5d18-4dc7-b4de-eb4baeac719d.png)


[노하우&팁]
![Image](https://user-images.githubusercontent.com/94954921/186557928-062a1be7-ad1d-4c68-bd7a-fbac17b40d8a.png)

**Comment by minnie8211** [comment]
2. 홈화면(어제 논의한 부분 외에 좀 더 들어가면 어떨까하는 부분을 추가해서 목업 만들어봤습니다)
5. 학습게시판 
   5-1. 학습게시판
       - 전체, 스터디, 프로젝트...등 탭 이동으로 해당 항목만 보일 수 있는 구성으로 작성했습니다.
   5-2. 학습게시판 글 상세보기
   5-3. 학습게시판 글 작성
      - 상단 스터디/프로젝트 버튼을 선택해서 글을 카테고리별로 등록할 수 있도록 구성 했습니다.
      - 스터디/프로젝트 모집 게시판의 성격에 맞도록 기본 입력 양식을 제공하는 형식으로 했습니다.
      



![Image](https://user-images.githubusercontent.com/100906856/186565708-27f1a374-3fcf-4e54-a393-5efa0f690745.jpg)



![Image](https://user-images.githubusercontent.com/100906856/186565724-47596ea7-82e8-400e-b9d3-510c457b3bad.jpg)



![Image](https://user-images.githubusercontent.com/100906856/186565736-9dba5bbb-55de-4147-acfd-fe8a31fe3b5e.jpg)



![Image](https://user-images.githubusercontent.com/100906856/186565749-bf8fa4ae-059b-46ca-bd60-af54c3092d60.jpg)

**Comment by oxoxhub** [comment]
6. 온라인 강의
강의소개와 커리큘럼은 비슷한 구조로 갈 것 같아서 일단 강의소개만 만들어두었습니다.
상단 메뉴와 하단 메뉴는 통일해야할 것 같아서 일단 빼두고 작성하였습니다.

![Image](https://user-images.githubusercontent.com/97341594/186592727-89e43d8a-701d-4620-938e-1f5e6845e4cf.png)



![Image](https://user-images.githubusercontent.com/97341594/186592753-24a2cefd-6ed0-463f-badd-0369a576c86d.png)



![Image](https://user-images.githubusercontent.com/97341594/186592782-f5650f31-df25-4d2e-95a0-6a938c47cc33.png)



![Image](https://user-images.githubusercontent.com/97341594/186592800-6ff77994-72a4-4ac1-98d6-276890731274.png)

**Comment by oni96oni** [comment]
![final_project  Untitled (1)](https://user-images.githubusercontent.com/95541472/186595176-d5c42d70-e9dd-402f-bbc4-32947d44e801.png)
sms 인증 기능 대비해서 전화번호 칸에 인증번호 받기 및 입력 넣어놨습니다.

**Comment by QQU2** [comment]
게시판
- tab을 통해 게시판 옮겨가기(게시판 자체? 게시판 하위 종류)
- 배너
- 검색창 ()
- 글쓰기 페이지: 글쓰기 페이지에서 어느 게시판에서 글쓰기 들어갔어도 세부 카테고리를 설정할 수 있도록 설정

**Comment by WinterStar915** [comment]
로그인 페이지 예시



![Image](https://user-images.githubusercontent.com/94954921/186614285-66462c30-de15-4394-ae66-37e53b23c59b.png)

**Comment by minnie8211** [comment]
어제 논의한 내용을 바탕으로 디자인 수정해보았습니다. 강의상세보기, 수강평, Q&A까지는 아직 못했구요.
일단 작업된 부분까지 공유합니다.


[메인페이지]
![Image](https://user-images.githubusercontent.com/100906856/186833074-7f98fa51-8c72-4ea8-9270-4d3276ead5be.jpg)


[로그인]
![Image](https://user-images.githubusercontent.com/100906856/186833108-3d875443-7b1d-4a0b-8c34-ec60ecae1c2c.jpg)


[회원가입]
![Image](https://user-images.githubusercontent.com/100906856/186833185-44cdb2cc-e2e4-4ae9-87bc-3502cbc5aef0.jpg)


[마이페이지_내게시글보기]
![Image](https://user-images.githubusercontent.com/100906856/186833495-db3b40d8-6356-47dd-bcab-1288e097086e.jpg)


[마이페이지_수강 중인 강의]
![Image](https://user-images.githubusercontent.com/100906856/186833536-ac88a7ef-d244-4688-ab0a-2854839c62ea.jpg)


[마이페이지_개인 정보 수정]
![Image](https://user-images.githubusercontent.com/100906856/186833601-2260d587-4aeb-475c-86f0-52e4f69f9a7f.jpg)


[커뮤니티 게시판]
![Image](https://user-images.githubusercontent.com/100906856/186833220-4d40e3d5-b8ed-47d1-83fe-33476487434b.jpg)


[학습 게시판]
![Image](https://user-images.githubusercontent.com/100906856/186833262-f56def6c-f27e-4d26-8d0d-ef9d50afa653.jpg)


[글 상세보기]
![Image](https://user-images.githubusercontent.com/100906856/186833313-ccb31c5f-56f8-4d22-a573-ef7b889659f1.jpg)


[커뮤니티 글쓰기]
![Image](https://user-images.githubusercontent.com/100906856/186833364-7098714a-2d9b-46ea-a7dc-22d16e762d6f.jpg)


[학습게시판 글쓰기]
![Image](https://user-images.githubusercontent.com/100906856/186833415-3022fd8a-9e89-4802-9dcb-32882d3dac7e.jpg)


[강의페이지]
![Image](https://user-images.githubusercontent.com/100906856/186833692-79ad33cf-1026-4f1c-84f7-c4d82fc5c13d.jpg)
